name = "JuliennedArrays"
uuid = "5cadff95-7770-533d-a838-a1bf817ee6e0"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com>"]
repo = "https://github.com/bramtayl/JuliennedArrays.jl.git"
version = "0.2.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
