name = "JuliennedArrays"
uuid = "5cadff95-7770-533d-a838-a1bf817ee6e0"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com>"]
version = "0.2.2"
repo = "https://github.com/bramtayl/JuliennedArrays.jl.git"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]

[compat]
julia = "1"
